/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 71
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 1
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym__newline_token1 = 1,
  sym__space = 2,
  sym__rest = 3,
  anon_sym_PERCENTjs = 4,
  anon_sym_PERCENTcss = 5,
  sym_plugin_name = 6,
  anon_sym_SLASH_SLASH = 7,
  anon_sym_SLASH = 8,
  sym_selector = 9,
  sym_binding = 10,
  sym_event = 11,
  sym_binding_args = 12,
  anon_sym_EQ = 13,
  anon_sym_BSLASH = 14,
  sym_block_body = 15,
  sym_block_empty_line = 16,
  sym_source_file = 17,
  sym__item = 18,
  sym__newline = 19,
  sym_js_block = 20,
  sym_css_block = 21,
  sym_plugin_line = 22,
  sym_comment = 23,
  sym_template_line = 24,
  aux_sym__binding_list = 25,
  sym_raw_text = 26,
  aux_sym_source_file_repeat1 = 27,
  aux_sym_js_block_repeat1 = 28,
  alias_sym_text_content = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__newline_token1] = "_newline_token1",
  [sym__space] = "_space",
  [sym__rest] = "_rest",
  [anon_sym_PERCENTjs] = "%js",
  [anon_sym_PERCENTcss] = "%css",
  [sym_plugin_name] = "plugin_name",
  [anon_sym_SLASH_SLASH] = "//",
  [anon_sym_SLASH] = "/",
  [sym_selector] = "selector",
  [sym_binding] = "binding",
  [sym_event] = "event",
  [sym_binding_args] = "binding_args",
  [anon_sym_EQ] = "= ",
  [anon_sym_BSLASH] = "\\ ",
  [sym_block_body] = "block_body",
  [sym_block_empty_line] = "block_empty_line",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym__newline] = "_newline",
  [sym_js_block] = "js_block",
  [sym_css_block] = "css_block",
  [sym_plugin_line] = "plugin_line",
  [sym_comment] = "comment",
  [sym_template_line] = "template_line",
  [aux_sym__binding_list] = "_binding_list",
  [sym_raw_text] = "raw_text",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_js_block_repeat1] = "js_block_repeat1",
  [alias_sym_text_content] = "text_content",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__newline_token1] = aux_sym__newline_token1,
  [sym__space] = sym__space,
  [sym__rest] = sym__rest,
  [anon_sym_PERCENTjs] = anon_sym_PERCENTjs,
  [anon_sym_PERCENTcss] = anon_sym_PERCENTcss,
  [sym_plugin_name] = sym_plugin_name,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_selector] = sym_selector,
  [sym_binding] = sym_binding,
  [sym_event] = sym_event,
  [sym_binding_args] = sym_binding_args,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [sym_block_body] = sym_block_body,
  [sym_block_empty_line] = sym_block_empty_line,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym__newline] = sym__newline,
  [sym_js_block] = sym_js_block,
  [sym_css_block] = sym_css_block,
  [sym_plugin_line] = sym_plugin_line,
  [sym_comment] = sym_comment,
  [sym_template_line] = sym_template_line,
  [aux_sym__binding_list] = aux_sym__binding_list,
  [sym_raw_text] = sym_raw_text,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_js_block_repeat1] = aux_sym_js_block_repeat1,
  [alias_sym_text_content] = alias_sym_text_content,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__newline_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym__rest] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PERCENTjs] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENTcss] = {
    .visible = true,
    .named = false,
  },
  [sym_plugin_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_event] = {
    .visible = true,
    .named = true,
  },
  [sym_binding_args] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_block_body] = {
    .visible = true,
    .named = true,
  },
  [sym_block_empty_line] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_js_block] = {
    .visible = true,
    .named = true,
  },
  [sym_css_block] = {
    .visible = true,
    .named = true,
  },
  [sym_plugin_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_template_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__binding_list] = {
    .visible = false,
    .named = false,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_js_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_text_content] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_plugin_name,
  },
  [2] = {
    [1] = alias_sym_text_content,
  },
  [3] = {
    [1] = sym_plugin_name,
  },
  [4] = {
    [2] = alias_sym_text_content,
  },
  [5] = {
    [3] = alias_sym_text_content,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '\n', 13,
        '%', 46,
        '/', 33,
        ';', 10,
        '=', 44,
        '@', 9,
        '\\', 45,
        '\t', 14,
        ' ', 14,
      );
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == ';') ADVANCE(10);
      if (lookahead == '@') ADVANCE(9);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == ';') ADVANCE(17);
      if (lookahead == '@') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '[') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(38);
      END_STATE();
    case 7:
      if (lookahead == '[') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(38);
      END_STATE();
    case 8:
      if (lookahead == ']') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(8);
      END_STATE();
    case 9:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 10:
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '\n', 13,
        '%', 37,
        '/', 34,
        ';', 10,
        '=', 35,
        '@', 9,
        '[', 8,
        '\\', 36,
        '\t', 14,
        ' ', 14,
      );
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym__newline_token1);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__rest);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym__rest);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym__rest);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_PERCENTjs);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '[') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(38);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_PERCENTjs);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_PERCENTcss);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '[') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(38);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_PERCENTcss);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '[') ADVANCE(8);
      if (lookahead == 's') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(38);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '[') ADVANCE(8);
      if (lookahead == 's') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(38);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '[') ADVANCE(8);
      if (lookahead == 's') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(38);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '[') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(38);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 's') ADVANCE(20);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 's') ADVANCE(22);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 's') ADVANCE(28);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_plugin_name);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '[') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(38);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(31);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '[') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(38);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_selector);
      if (lookahead == '\t') ADVANCE(5);
      if (lookahead == ' ') ADVANCE(49);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '[') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(38);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_selector);
      if (lookahead == '\t') ADVANCE(5);
      if (lookahead == ' ') ADVANCE(51);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '[') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(38);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_selector);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '[') ADVANCE(8);
      if (lookahead == 'c') ADVANCE(25);
      if (lookahead == 'j') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_selector);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '[') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_selector);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '[') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(38);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_binding);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_binding);
      if (lookahead == '!' ||
          lookahead == ':') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_event);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_event);
      if (lookahead == '!' ||
          lookahead == ':') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_binding_args);
      if (lookahead == ' ') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(47);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_binding_args);
      if (lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(47);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_binding_args);
      if (lookahead == 'c') ADVANCE(29);
      if (lookahead == 'j') ADVANCE(27);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_binding_args);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == '>') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11, .external_lex_state = 1},
  [5] = {.lex_state = 11, .external_lex_state = 1},
  [6] = {.lex_state = 11, .external_lex_state = 1},
  [7] = {.lex_state = 11, .external_lex_state = 1},
  [8] = {.lex_state = 11, .external_lex_state = 1},
  [9] = {.lex_state = 11, .external_lex_state = 1},
  [10] = {.lex_state = 11, .external_lex_state = 1},
  [11] = {.lex_state = 11},
  [12] = {.lex_state = 11},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 11},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 11},
  [17] = {.lex_state = 11},
  [18] = {.lex_state = 11},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 11},
  [21] = {.lex_state = 11},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 11},
  [24] = {.lex_state = 11},
  [25] = {.lex_state = 11},
  [26] = {.lex_state = 11},
  [27] = {.lex_state = 11},
  [28] = {.lex_state = 11},
  [29] = {.lex_state = 11},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0, .external_lex_state = 1},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 0, .external_lex_state = 1},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 11},
  [52] = {.lex_state = 11},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym__newline_token1] = ACTIONS(1),
    [sym__space] = ACTIONS(1),
    [anon_sym_PERCENTjs] = ACTIONS(1),
    [anon_sym_PERCENTcss] = ACTIONS(1),
    [sym_plugin_name] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_binding] = ACTIONS(1),
    [sym_event] = ACTIONS(1),
    [sym_binding_args] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [sym_block_body] = ACTIONS(1),
    [sym_block_empty_line] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(58),
    [sym__item] = STATE(3),
    [sym__newline] = STATE(3),
    [sym_js_block] = STATE(3),
    [sym_css_block] = STATE(3),
    [sym_plugin_line] = STATE(3),
    [sym_comment] = STATE(3),
    [sym_template_line] = STATE(3),
    [aux_sym__binding_list] = STATE(33),
    [sym_raw_text] = STATE(54),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym__newline_token1] = ACTIONS(5),
    [sym__space] = ACTIONS(7),
    [anon_sym_PERCENTjs] = ACTIONS(9),
    [anon_sym_PERCENTcss] = ACTIONS(11),
    [sym_plugin_name] = ACTIONS(13),
    [anon_sym_SLASH_SLASH] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [sym_selector] = ACTIONS(17),
    [sym_binding] = ACTIONS(19),
    [sym_event] = ACTIONS(19),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_BSLASH] = ACTIONS(21),
  },
  [STATE(2)] = {
    [sym__item] = STATE(2),
    [sym__newline] = STATE(2),
    [sym_js_block] = STATE(2),
    [sym_css_block] = STATE(2),
    [sym_plugin_line] = STATE(2),
    [sym_comment] = STATE(2),
    [sym_template_line] = STATE(2),
    [aux_sym__binding_list] = STATE(33),
    [sym_raw_text] = STATE(54),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(23),
    [aux_sym__newline_token1] = ACTIONS(25),
    [sym__space] = ACTIONS(28),
    [anon_sym_PERCENTjs] = ACTIONS(31),
    [anon_sym_PERCENTcss] = ACTIONS(34),
    [sym_plugin_name] = ACTIONS(37),
    [anon_sym_SLASH_SLASH] = ACTIONS(40),
    [anon_sym_SLASH] = ACTIONS(40),
    [sym_selector] = ACTIONS(43),
    [sym_binding] = ACTIONS(46),
    [sym_event] = ACTIONS(46),
    [anon_sym_EQ] = ACTIONS(49),
    [anon_sym_BSLASH] = ACTIONS(49),
  },
  [STATE(3)] = {
    [sym__item] = STATE(2),
    [sym__newline] = STATE(2),
    [sym_js_block] = STATE(2),
    [sym_css_block] = STATE(2),
    [sym_plugin_line] = STATE(2),
    [sym_comment] = STATE(2),
    [sym_template_line] = STATE(2),
    [aux_sym__binding_list] = STATE(33),
    [sym_raw_text] = STATE(54),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(52),
    [aux_sym__newline_token1] = ACTIONS(54),
    [sym__space] = ACTIONS(7),
    [anon_sym_PERCENTjs] = ACTIONS(9),
    [anon_sym_PERCENTcss] = ACTIONS(11),
    [sym_plugin_name] = ACTIONS(13),
    [anon_sym_SLASH_SLASH] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [sym_selector] = ACTIONS(17),
    [sym_binding] = ACTIONS(19),
    [sym_event] = ACTIONS(19),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_BSLASH] = ACTIONS(21),
  },
  [STATE(4)] = {
    [aux_sym_js_block_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(56),
    [aux_sym__newline_token1] = ACTIONS(56),
    [sym__space] = ACTIONS(56),
    [anon_sym_PERCENTjs] = ACTIONS(58),
    [anon_sym_PERCENTcss] = ACTIONS(58),
    [sym_plugin_name] = ACTIONS(58),
    [anon_sym_SLASH_SLASH] = ACTIONS(58),
    [anon_sym_SLASH] = ACTIONS(58),
    [sym_selector] = ACTIONS(58),
    [sym_binding] = ACTIONS(56),
    [sym_event] = ACTIONS(56),
    [anon_sym_EQ] = ACTIONS(58),
    [anon_sym_BSLASH] = ACTIONS(58),
    [sym_block_body] = ACTIONS(60),
    [sym_block_empty_line] = ACTIONS(60),
  },
  [STATE(5)] = {
    [aux_sym_js_block_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(56),
    [aux_sym__newline_token1] = ACTIONS(56),
    [sym__space] = ACTIONS(56),
    [anon_sym_PERCENTjs] = ACTIONS(58),
    [anon_sym_PERCENTcss] = ACTIONS(58),
    [sym_plugin_name] = ACTIONS(58),
    [anon_sym_SLASH_SLASH] = ACTIONS(58),
    [anon_sym_SLASH] = ACTIONS(58),
    [sym_selector] = ACTIONS(58),
    [sym_binding] = ACTIONS(56),
    [sym_event] = ACTIONS(56),
    [anon_sym_EQ] = ACTIONS(58),
    [anon_sym_BSLASH] = ACTIONS(58),
    [sym_block_body] = ACTIONS(62),
    [sym_block_empty_line] = ACTIONS(62),
  },
  [STATE(6)] = {
    [aux_sym_js_block_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(64),
    [aux_sym__newline_token1] = ACTIONS(64),
    [sym__space] = ACTIONS(64),
    [anon_sym_PERCENTjs] = ACTIONS(66),
    [anon_sym_PERCENTcss] = ACTIONS(66),
    [sym_plugin_name] = ACTIONS(66),
    [anon_sym_SLASH_SLASH] = ACTIONS(66),
    [anon_sym_SLASH] = ACTIONS(66),
    [sym_selector] = ACTIONS(66),
    [sym_binding] = ACTIONS(64),
    [sym_event] = ACTIONS(64),
    [anon_sym_EQ] = ACTIONS(66),
    [anon_sym_BSLASH] = ACTIONS(66),
    [sym_block_body] = ACTIONS(68),
    [sym_block_empty_line] = ACTIONS(68),
  },
  [STATE(7)] = {
    [aux_sym_js_block_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(70),
    [aux_sym__newline_token1] = ACTIONS(70),
    [sym__space] = ACTIONS(70),
    [anon_sym_PERCENTjs] = ACTIONS(72),
    [anon_sym_PERCENTcss] = ACTIONS(72),
    [sym_plugin_name] = ACTIONS(72),
    [anon_sym_SLASH_SLASH] = ACTIONS(72),
    [anon_sym_SLASH] = ACTIONS(72),
    [sym_selector] = ACTIONS(72),
    [sym_binding] = ACTIONS(70),
    [sym_event] = ACTIONS(70),
    [anon_sym_EQ] = ACTIONS(72),
    [anon_sym_BSLASH] = ACTIONS(72),
    [sym_block_body] = ACTIONS(68),
    [sym_block_empty_line] = ACTIONS(68),
  },
  [STATE(8)] = {
    [aux_sym_js_block_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(74),
    [aux_sym__newline_token1] = ACTIONS(74),
    [sym__space] = ACTIONS(74),
    [anon_sym_PERCENTjs] = ACTIONS(76),
    [anon_sym_PERCENTcss] = ACTIONS(76),
    [sym_plugin_name] = ACTIONS(76),
    [anon_sym_SLASH_SLASH] = ACTIONS(76),
    [anon_sym_SLASH] = ACTIONS(76),
    [sym_selector] = ACTIONS(76),
    [sym_binding] = ACTIONS(74),
    [sym_event] = ACTIONS(74),
    [anon_sym_EQ] = ACTIONS(76),
    [anon_sym_BSLASH] = ACTIONS(76),
    [sym_block_body] = ACTIONS(78),
    [sym_block_empty_line] = ACTIONS(78),
  },
  [STATE(9)] = {
    [aux_sym_js_block_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(81),
    [aux_sym__newline_token1] = ACTIONS(81),
    [sym__space] = ACTIONS(81),
    [anon_sym_PERCENTjs] = ACTIONS(83),
    [anon_sym_PERCENTcss] = ACTIONS(83),
    [sym_plugin_name] = ACTIONS(83),
    [anon_sym_SLASH_SLASH] = ACTIONS(83),
    [anon_sym_SLASH] = ACTIONS(83),
    [sym_selector] = ACTIONS(83),
    [sym_binding] = ACTIONS(81),
    [sym_event] = ACTIONS(81),
    [anon_sym_EQ] = ACTIONS(83),
    [anon_sym_BSLASH] = ACTIONS(83),
    [sym_block_body] = ACTIONS(68),
    [sym_block_empty_line] = ACTIONS(68),
  },
  [STATE(10)] = {
    [aux_sym_js_block_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(85),
    [aux_sym__newline_token1] = ACTIONS(85),
    [sym__space] = ACTIONS(85),
    [anon_sym_PERCENTjs] = ACTIONS(87),
    [anon_sym_PERCENTcss] = ACTIONS(87),
    [sym_plugin_name] = ACTIONS(87),
    [anon_sym_SLASH_SLASH] = ACTIONS(87),
    [anon_sym_SLASH] = ACTIONS(87),
    [sym_selector] = ACTIONS(87),
    [sym_binding] = ACTIONS(85),
    [sym_event] = ACTIONS(85),
    [anon_sym_EQ] = ACTIONS(87),
    [anon_sym_BSLASH] = ACTIONS(87),
    [sym_block_body] = ACTIONS(68),
    [sym_block_empty_line] = ACTIONS(68),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(89), 5,
      ts_builtin_sym_end,
      aux_sym__newline_token1,
      sym__space,
      sym_binding,
      sym_event,
    ACTIONS(91), 8,
      anon_sym_PERCENTjs,
      anon_sym_PERCENTcss,
      sym_plugin_name,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      sym_selector,
      anon_sym_EQ,
      anon_sym_BSLASH,
  [18] = 2,
    ACTIONS(93), 5,
      ts_builtin_sym_end,
      aux_sym__newline_token1,
      sym__space,
      sym_binding,
      sym_event,
    ACTIONS(95), 8,
      anon_sym_PERCENTjs,
      anon_sym_PERCENTcss,
      sym_plugin_name,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      sym_selector,
      anon_sym_EQ,
      anon_sym_BSLASH,
  [36] = 2,
    ACTIONS(97), 5,
      ts_builtin_sym_end,
      aux_sym__newline_token1,
      sym__space,
      sym_binding,
      sym_event,
    ACTIONS(99), 8,
      anon_sym_PERCENTjs,
      anon_sym_PERCENTcss,
      sym_plugin_name,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      sym_selector,
      anon_sym_EQ,
      anon_sym_BSLASH,
  [54] = 2,
    ACTIONS(101), 5,
      ts_builtin_sym_end,
      aux_sym__newline_token1,
      sym__space,
      sym_binding,
      sym_event,
    ACTIONS(103), 8,
      anon_sym_PERCENTjs,
      anon_sym_PERCENTcss,
      sym_plugin_name,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      sym_selector,
      anon_sym_EQ,
      anon_sym_BSLASH,
  [72] = 2,
    ACTIONS(105), 5,
      ts_builtin_sym_end,
      aux_sym__newline_token1,
      sym__space,
      sym_binding,
      sym_event,
    ACTIONS(107), 8,
      anon_sym_PERCENTjs,
      anon_sym_PERCENTcss,
      sym_plugin_name,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      sym_selector,
      anon_sym_EQ,
      anon_sym_BSLASH,
  [90] = 2,
    ACTIONS(109), 5,
      ts_builtin_sym_end,
      aux_sym__newline_token1,
      sym__space,
      sym_binding,
      sym_event,
    ACTIONS(111), 8,
      anon_sym_PERCENTjs,
      anon_sym_PERCENTcss,
      sym_plugin_name,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      sym_selector,
      anon_sym_EQ,
      anon_sym_BSLASH,
  [108] = 2,
    ACTIONS(113), 5,
      ts_builtin_sym_end,
      aux_sym__newline_token1,
      sym__space,
      sym_binding,
      sym_event,
    ACTIONS(115), 8,
      anon_sym_PERCENTjs,
      anon_sym_PERCENTcss,
      sym_plugin_name,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      sym_selector,
      anon_sym_EQ,
      anon_sym_BSLASH,
  [126] = 2,
    ACTIONS(117), 5,
      ts_builtin_sym_end,
      aux_sym__newline_token1,
      sym__space,
      sym_binding,
      sym_event,
    ACTIONS(119), 8,
      anon_sym_PERCENTjs,
      anon_sym_PERCENTcss,
      sym_plugin_name,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      sym_selector,
      anon_sym_EQ,
      anon_sym_BSLASH,
  [144] = 2,
    ACTIONS(121), 5,
      ts_builtin_sym_end,
      aux_sym__newline_token1,
      sym__space,
      sym_binding,
      sym_event,
    ACTIONS(123), 8,
      anon_sym_PERCENTjs,
      anon_sym_PERCENTcss,
      sym_plugin_name,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      sym_selector,
      anon_sym_EQ,
      anon_sym_BSLASH,
  [162] = 2,
    ACTIONS(125), 5,
      ts_builtin_sym_end,
      aux_sym__newline_token1,
      sym__space,
      sym_binding,
      sym_event,
    ACTIONS(127), 8,
      anon_sym_PERCENTjs,
      anon_sym_PERCENTcss,
      sym_plugin_name,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      sym_selector,
      anon_sym_EQ,
      anon_sym_BSLASH,
  [180] = 2,
    ACTIONS(129), 5,
      ts_builtin_sym_end,
      aux_sym__newline_token1,
      sym__space,
      sym_binding,
      sym_event,
    ACTIONS(131), 8,
      anon_sym_PERCENTjs,
      anon_sym_PERCENTcss,
      sym_plugin_name,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      sym_selector,
      anon_sym_EQ,
      anon_sym_BSLASH,
  [198] = 2,
    ACTIONS(133), 5,
      ts_builtin_sym_end,
      aux_sym__newline_token1,
      sym__space,
      sym_binding,
      sym_event,
    ACTIONS(135), 8,
      anon_sym_PERCENTjs,
      anon_sym_PERCENTcss,
      sym_plugin_name,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      sym_selector,
      anon_sym_EQ,
      anon_sym_BSLASH,
  [216] = 2,
    ACTIONS(137), 5,
      ts_builtin_sym_end,
      aux_sym__newline_token1,
      sym__space,
      sym_binding,
      sym_event,
    ACTIONS(139), 8,
      anon_sym_PERCENTjs,
      anon_sym_PERCENTcss,
      sym_plugin_name,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      sym_selector,
      anon_sym_EQ,
      anon_sym_BSLASH,
  [234] = 2,
    ACTIONS(141), 5,
      ts_builtin_sym_end,
      aux_sym__newline_token1,
      sym__space,
      sym_binding,
      sym_event,
    ACTIONS(143), 8,
      anon_sym_PERCENTjs,
      anon_sym_PERCENTcss,
      sym_plugin_name,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      sym_selector,
      anon_sym_EQ,
      anon_sym_BSLASH,
  [252] = 2,
    ACTIONS(145), 5,
      ts_builtin_sym_end,
      aux_sym__newline_token1,
      sym__space,
      sym_binding,
      sym_event,
    ACTIONS(147), 8,
      anon_sym_PERCENTjs,
      anon_sym_PERCENTcss,
      sym_plugin_name,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      sym_selector,
      anon_sym_EQ,
      anon_sym_BSLASH,
  [270] = 2,
    ACTIONS(149), 5,
      ts_builtin_sym_end,
      aux_sym__newline_token1,
      sym__space,
      sym_binding,
      sym_event,
    ACTIONS(151), 8,
      anon_sym_PERCENTjs,
      anon_sym_PERCENTcss,
      sym_plugin_name,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      sym_selector,
      anon_sym_EQ,
      anon_sym_BSLASH,
  [288] = 2,
    ACTIONS(153), 5,
      ts_builtin_sym_end,
      aux_sym__newline_token1,
      sym__space,
      sym_binding,
      sym_event,
    ACTIONS(155), 8,
      anon_sym_PERCENTjs,
      anon_sym_PERCENTcss,
      sym_plugin_name,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      sym_selector,
      anon_sym_EQ,
      anon_sym_BSLASH,
  [306] = 2,
    ACTIONS(157), 5,
      ts_builtin_sym_end,
      aux_sym__newline_token1,
      sym__space,
      sym_binding,
      sym_event,
    ACTIONS(159), 8,
      anon_sym_PERCENTjs,
      anon_sym_PERCENTcss,
      sym_plugin_name,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      sym_selector,
      anon_sym_EQ,
      anon_sym_BSLASH,
  [324] = 8,
    ACTIONS(163), 1,
      sym_plugin_name,
    ACTIONS(167), 1,
      sym_selector,
    STATE(37), 1,
      aux_sym__binding_list,
    STATE(62), 1,
      sym_raw_text,
    ACTIONS(19), 2,
      sym_binding,
      sym_event,
    ACTIONS(21), 2,
      anon_sym_EQ,
      anon_sym_BSLASH,
    ACTIONS(161), 2,
      anon_sym_PERCENTjs,
      anon_sym_PERCENTcss,
    ACTIONS(165), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
  [353] = 3,
    ACTIONS(169), 1,
      aux_sym__newline_token1,
    STATE(32), 1,
      aux_sym__binding_list,
    ACTIONS(19), 2,
      sym_binding,
      sym_event,
  [364] = 2,
    ACTIONS(173), 1,
      sym_binding_args,
    ACTIONS(171), 3,
      aux_sym__newline_token1,
      sym_binding,
      sym_event,
  [373] = 3,
    ACTIONS(175), 1,
      aux_sym__newline_token1,
    STATE(32), 1,
      aux_sym__binding_list,
    ACTIONS(177), 2,
      sym_binding,
      sym_event,
  [384] = 3,
    ACTIONS(180), 1,
      aux_sym__newline_token1,
    STATE(32), 1,
      aux_sym__binding_list,
    ACTIONS(19), 2,
      sym_binding,
      sym_event,
  [395] = 3,
    ACTIONS(182), 1,
      sym__rest,
    STATE(30), 1,
      aux_sym__binding_list,
    ACTIONS(19), 2,
      sym_binding,
      sym_event,
  [406] = 3,
    ACTIONS(184), 1,
      sym__rest,
    STATE(36), 1,
      aux_sym__binding_list,
    ACTIONS(19), 2,
      sym_binding,
      sym_event,
  [417] = 3,
    ACTIONS(186), 1,
      aux_sym__newline_token1,
    STATE(32), 1,
      aux_sym__binding_list,
    ACTIONS(19), 2,
      sym_binding,
      sym_event,
  [428] = 3,
    ACTIONS(188), 1,
      aux_sym__newline_token1,
    STATE(32), 1,
      aux_sym__binding_list,
    ACTIONS(19), 2,
      sym_binding,
      sym_event,
  [439] = 2,
    STATE(10), 1,
      aux_sym_js_block_repeat1,
    ACTIONS(190), 2,
      sym_block_body,
      sym_block_empty_line,
  [447] = 1,
    ACTIONS(175), 3,
      aux_sym__newline_token1,
      sym_binding,
      sym_event,
  [453] = 3,
    ACTIONS(192), 1,
      aux_sym__newline_token1,
    ACTIONS(194), 1,
      sym__space,
    ACTIONS(196), 1,
      sym__rest,
  [463] = 3,
    ACTIONS(198), 1,
      aux_sym__newline_token1,
    ACTIONS(200), 1,
      sym__space,
    ACTIONS(202), 1,
      sym__rest,
  [473] = 2,
    STATE(7), 1,
      aux_sym_js_block_repeat1,
    ACTIONS(204), 2,
      sym_block_body,
      sym_block_empty_line,
  [481] = 3,
    ACTIONS(206), 1,
      aux_sym__newline_token1,
    ACTIONS(208), 1,
      sym__space,
    ACTIONS(210), 1,
      sym__rest,
  [491] = 3,
    ACTIONS(210), 1,
      sym__rest,
    ACTIONS(212), 1,
      aux_sym__newline_token1,
    ACTIONS(214), 1,
      sym__space,
  [501] = 3,
    ACTIONS(216), 1,
      aux_sym__newline_token1,
    ACTIONS(218), 1,
      sym__space,
    ACTIONS(220), 1,
      sym__rest,
  [511] = 2,
    ACTIONS(222), 1,
      aux_sym__newline_token1,
    ACTIONS(224), 1,
      sym__rest,
  [518] = 2,
    ACTIONS(226), 1,
      aux_sym__newline_token1,
    ACTIONS(228), 1,
      sym__rest,
  [525] = 2,
    ACTIONS(230), 1,
      aux_sym__newline_token1,
    ACTIONS(232), 1,
      sym__rest,
  [532] = 2,
    ACTIONS(234), 1,
      aux_sym__newline_token1,
    ACTIONS(236), 1,
      sym__rest,
  [539] = 2,
    ACTIONS(232), 1,
      sym__rest,
    ACTIONS(238), 1,
      aux_sym__newline_token1,
  [546] = 2,
    ACTIONS(188), 1,
      aux_sym__newline_token1,
    ACTIONS(240), 1,
      sym__space,
  [553] = 2,
    ACTIONS(180), 1,
      aux_sym__newline_token1,
    ACTIONS(242), 1,
      sym__space,
  [560] = 1,
    ACTIONS(244), 1,
      aux_sym__newline_token1,
  [564] = 1,
    ACTIONS(180), 1,
      aux_sym__newline_token1,
  [568] = 1,
    ACTIONS(246), 1,
      aux_sym__newline_token1,
  [572] = 1,
    ACTIONS(248), 1,
      sym__rest,
  [576] = 1,
    ACTIONS(250), 1,
      aux_sym__newline_token1,
  [580] = 1,
    ACTIONS(252), 1,
      ts_builtin_sym_end,
  [584] = 1,
    ACTIONS(254), 1,
      aux_sym__newline_token1,
  [588] = 1,
    ACTIONS(256), 1,
      sym__rest,
  [592] = 1,
    ACTIONS(258), 1,
      aux_sym__newline_token1,
  [596] = 1,
    ACTIONS(188), 1,
      aux_sym__newline_token1,
  [600] = 1,
    ACTIONS(260), 1,
      aux_sym__newline_token1,
  [604] = 1,
    ACTIONS(262), 1,
      aux_sym__newline_token1,
  [608] = 1,
    ACTIONS(264), 1,
      aux_sym__newline_token1,
  [612] = 1,
    ACTIONS(266), 1,
      aux_sym__newline_token1,
  [616] = 1,
    ACTIONS(268), 1,
      sym__rest,
  [620] = 1,
    ACTIONS(192), 1,
      aux_sym__newline_token1,
  [624] = 1,
    ACTIONS(222), 1,
      aux_sym__newline_token1,
  [628] = 1,
    ACTIONS(270), 1,
      aux_sym__newline_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 18,
  [SMALL_STATE(13)] = 36,
  [SMALL_STATE(14)] = 54,
  [SMALL_STATE(15)] = 72,
  [SMALL_STATE(16)] = 90,
  [SMALL_STATE(17)] = 108,
  [SMALL_STATE(18)] = 126,
  [SMALL_STATE(19)] = 144,
  [SMALL_STATE(20)] = 162,
  [SMALL_STATE(21)] = 180,
  [SMALL_STATE(22)] = 198,
  [SMALL_STATE(23)] = 216,
  [SMALL_STATE(24)] = 234,
  [SMALL_STATE(25)] = 252,
  [SMALL_STATE(26)] = 270,
  [SMALL_STATE(27)] = 288,
  [SMALL_STATE(28)] = 306,
  [SMALL_STATE(29)] = 324,
  [SMALL_STATE(30)] = 353,
  [SMALL_STATE(31)] = 364,
  [SMALL_STATE(32)] = 373,
  [SMALL_STATE(33)] = 384,
  [SMALL_STATE(34)] = 395,
  [SMALL_STATE(35)] = 406,
  [SMALL_STATE(36)] = 417,
  [SMALL_STATE(37)] = 428,
  [SMALL_STATE(38)] = 439,
  [SMALL_STATE(39)] = 447,
  [SMALL_STATE(40)] = 453,
  [SMALL_STATE(41)] = 463,
  [SMALL_STATE(42)] = 473,
  [SMALL_STATE(43)] = 481,
  [SMALL_STATE(44)] = 491,
  [SMALL_STATE(45)] = 501,
  [SMALL_STATE(46)] = 511,
  [SMALL_STATE(47)] = 518,
  [SMALL_STATE(48)] = 525,
  [SMALL_STATE(49)] = 532,
  [SMALL_STATE(50)] = 539,
  [SMALL_STATE(51)] = 546,
  [SMALL_STATE(52)] = 553,
  [SMALL_STATE(53)] = 560,
  [SMALL_STATE(54)] = 564,
  [SMALL_STATE(55)] = 568,
  [SMALL_STATE(56)] = 572,
  [SMALL_STATE(57)] = 576,
  [SMALL_STATE(58)] = 580,
  [SMALL_STATE(59)] = 584,
  [SMALL_STATE(60)] = 588,
  [SMALL_STATE(61)] = 592,
  [SMALL_STATE(62)] = 596,
  [SMALL_STATE(63)] = 600,
  [SMALL_STATE(64)] = 604,
  [SMALL_STATE(65)] = 608,
  [SMALL_STATE(66)] = 612,
  [SMALL_STATE(67)] = 616,
  [SMALL_STATE(68)] = 620,
  [SMALL_STATE(69)] = 624,
  [SMALL_STATE(70)] = 628,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plugin_line, 2, 0, 1),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_plugin_line, 2, 0, 1),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_js_block, 3, 1, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_js_block, 3, 1, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_js_block, 4, 1, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_js_block, 4, 1, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_js_block_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_js_block_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_js_block_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_css_block, 3, 1, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_css_block, 3, 1, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_css_block, 4, 1, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_css_block, 4, 1, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plugin_line, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_plugin_line, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plugin_line, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_plugin_line, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_line, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_line, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plugin_line, 3, 0, 3),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_plugin_line, 3, 0, 3),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_line, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_line, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plugin_line, 3, 0, 1),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_plugin_line, 3, 0, 1),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 4, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 4, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plugin_line, 4, 0, 3),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_plugin_line, 4, 0, 3),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plugin_line, 4, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_plugin_line, 4, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plugin_line, 4, 0, 1),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_plugin_line, 4, 0, 1),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_line, 4, 0, 4),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_line, 4, 0, 4),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_line, 4, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_line, 4, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plugin_line, 5, 0, 3),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_plugin_line, 5, 0, 3),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plugin_line, 5, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_plugin_line, 5, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_line, 5, 0, 5),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_line, 5, 0, 5),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_line, 5, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_line, 5, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__binding_list, 1, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__binding_list, 2, 0, 0),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__binding_list, 2, 0, 0), SHIFT_REPEAT(31),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [208] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [210] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_text, 1, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [252] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_text, 2, 0, 2),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_block_body = 0,
  ts_external_token_block_empty_line = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_block_body] = sym_block_body,
  [ts_external_token_block_empty_line] = sym_block_empty_line,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_block_body] = true,
    [ts_external_token_block_empty_line] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_litejs_external_scanner_create(void);
void tree_sitter_litejs_external_scanner_destroy(void *);
bool tree_sitter_litejs_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_litejs_external_scanner_serialize(void *, char *);
void tree_sitter_litejs_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_litejs(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_litejs_external_scanner_create,
      tree_sitter_litejs_external_scanner_destroy,
      tree_sitter_litejs_external_scanner_scan,
      tree_sitter_litejs_external_scanner_serialize,
      tree_sitter_litejs_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "litejs",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 26,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
